// <auto-generated />
using System;
using InteractHub.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace InteractHub.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("InteractHub.API.Models.AppUser", b =>
            {
                b.Property<string>("Id").HasColumnType("nvarchar(450)");
                b.Property<string>("FullName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Bio").HasMaxLength(300).HasColumnType("nvarchar(300)");
                b.Property<string>("AvatarUrl").HasColumnType("nvarchar(max)");
                b.Property<string>("CoverUrl").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<bool>("IsActive").HasColumnType("bit");
                b.HasKey("Id");
                b.ToTable("AspNetUsers");
            });

            modelBuilder.Entity("InteractHub.API.Models.Post", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                b.Property<string>("Content").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                b.Property<string>("ImageUrl").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                b.Property<bool>("IsDeleted").HasColumnType("bit");
                b.Property<string>("UserId").IsRequired().HasColumnType("nvarchar(450)");
                b.HasKey("Id");
                b.HasIndex("UserId");
                b.ToTable("Posts");
            });
#pragma warning restore 612, 618
        }
    }
}
